name: CI - Spring Boot Gradle

on:
  push:
    branches:
      - main
      - develop
      - qa
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and test with Gradle
        run: ./gradlew build --no-daemon
